package View;

/**
 *
 * @author Katt
 */
public class ConfiguracionJuego extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDeInicio
     */
    public ConfiguracionJuego() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        RegresarFondo = new View.clases.PanelRound();
        BotonRegresar = new javax.swing.JButton();
        FondoCodigo = new View.clases.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        FondoGris = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        NumeroJugadores = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound1 = new View.clases.PanelRound();
        BotonListo = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Comodines = new javax.swing.JLabel();
        RangoFichas = new javax.swing.JLabel();
        botonMasRango = new javax.swing.JButton();
        botonMenosComodin = new javax.swing.JButton();
        botonMasComodin1 = new javax.swing.JButton();
        botonMenosRango = new javax.swing.JButton();
        FondoPt1 = new javax.swing.JLabel();
        FondoPt2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarFondo.setBackground(new java.awt.Color(217, 217, 217));
        RegresarFondo.setRoundBottomLeft(100);
        RegresarFondo.setRoundBottomRight(100);
        RegresarFondo.setRoundTopLeft(100);
        RegresarFondo.setRoundTopRight(100);

        BotonRegresar.setBackground(new java.awt.Color(217, 217, 217));
        BotonRegresar.setFont(new java.awt.Font("Lucida Fax", 1, 36)); // NOI18N
        BotonRegresar.setBorder(null);
        BotonRegresar.setBorderPainted(false);
        BotonRegresar.setContentAreaFilled(false);
        BotonRegresar.setFocusPainted(false);
        BotonRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonRegresar.setLabel("<-");
        BotonRegresar.setRequestFocusEnabled(false);
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegresarFondoLayout = new javax.swing.GroupLayout(RegresarFondo);
        RegresarFondo.setLayout(RegresarFondoLayout);
        RegresarFondoLayout.setHorizontalGroup(
            RegresarFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegresarFondoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BotonRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        RegresarFondoLayout.setVerticalGroup(
            RegresarFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegresarFondoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BotonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        Fondo.add(RegresarFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 80, 80));

        FondoCodigo.setBackground(new java.awt.Color(217, 217, 217));
        FondoCodigo.setRoundBottomLeft(50);
        FondoCodigo.setRoundBottomRight(50);
        FondoCodigo.setRoundTopLeft(50);
        FondoCodigo.setRoundTopRight(50);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        jLabel1.setText("Codigo para Unirse:");

        Codigo.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        Codigo.setForeground(new java.awt.Color(90, 36, 159));
        Codigo.setText("Codigo");

        javax.swing.GroupLayout FondoCodigoLayout = new javax.swing.GroupLayout(FondoCodigo);
        FondoCodigo.setLayout(FondoCodigoLayout);
        FondoCodigoLayout.setHorizontalGroup(
            FondoCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoCodigoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Codigo)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        FondoCodigoLayout.setVerticalGroup(
            FondoCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(Codigo))
        );

        Fondo.add(FondoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 430, 50));

        FondoGris.setBackground(new java.awt.Color(217, 217, 217));
        FondoGris.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/UserIcon.png"))); // NOI18N

        NumeroJugadores.setFont(new java.awt.Font("Lucida Fax", 0, 18)); // NOI18N
        NumeroJugadores.setText("Numero / Numero");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 1, 30)); // NOI18N
        jLabel5.setText("Paleta de Colores ");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 1, 30)); // NOI18N
        jLabel6.setText("de las Fichas");

        panelRound1.setBackground(new java.awt.Color(143, 143, 143));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);

        BotonListo.setBackground(new java.awt.Color(143, 143, 143));
        BotonListo.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        BotonListo.setText("Listo");
        BotonListo.setBorder(null);
        BotonListo.setBorderPainted(false);
        BotonListo.setContentAreaFilled(false);
        BotonListo.setFocusPainted(false);
        BotonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BotonListo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonListo, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jComboBox1.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jComboBox1.setMaximumRowCount(4);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paleta de Colores 1", "Paleta de Colores 2", "Paleta de Colores 3", "Paleta de Colores 4" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.setDoubleBuffered(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel2.setText("Numero de");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel3.setText("Comodines");

        jLabel7.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel7.setText("Rango de ");

        jLabel8.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel8.setText("Fichas");

        jLabel9.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel9.setText(":");

        jLabel10.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        jLabel10.setText(":");

        Comodines.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        Comodines.setText("2");

        RangoFichas.setFont(new java.awt.Font("Lucida Fax", 1, 26)); // NOI18N
        RangoFichas.setText("13");

        botonMasRango.setBackground(new java.awt.Color(217, 217, 217));
        botonMasRango.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        botonMasRango.setText("+");
        botonMasRango.setBorder(null);
        botonMasRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasRangoActionPerformed(evt);
            }
        });

        botonMenosComodin.setBackground(new java.awt.Color(217, 217, 217));
        botonMenosComodin.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        botonMenosComodin.setText("—");
        botonMenosComodin.setBorder(null);
        botonMenosComodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosComodinActionPerformed(evt);
            }
        });

        botonMasComodin1.setBackground(new java.awt.Color(217, 217, 217));
        botonMasComodin1.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        botonMasComodin1.setText("+");
        botonMasComodin1.setBorder(null);
        botonMasComodin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasComodin1ActionPerformed(evt);
            }
        });

        botonMenosRango.setBackground(new java.awt.Color(217, 217, 217));
        botonMenosRango.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        botonMenosRango.setText("—");
        botonMenosRango.setBorder(null);
        botonMenosRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosRangoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoGrisLayout = new javax.swing.GroupLayout(FondoGris);
        FondoGris.setLayout(FondoGrisLayout);
        FondoGrisLayout.setHorizontalGroup(
            FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoGrisLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(FondoGrisLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RangoFichas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonMasRango))
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Comodines)
                        .addGap(32, 32, 32)
                        .addComponent(botonMasComodin1)))
                .addGap(18, 18, 18)
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMenosComodin)
                    .addComponent(botonMenosRango))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoGrisLayout.createSequentialGroup()
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6))
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NumeroJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        FondoGrisLayout.setVerticalGroup(
            FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoGrisLayout.createSequentialGroup()
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoGrisLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39))
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoGrisLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FondoGrisLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(FondoGrisLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(Comodines)
                                            .addComponent(botonMenosComodin)
                                            .addComponent(botonMasComodin1)))))
                            .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(FondoGrisLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(FondoGrisLayout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(NumeroJugadores))))
                        .addGap(41, 41, 41)))
                .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelRound1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoGrisLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)))
                    .addGroup(FondoGrisLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(FondoGrisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(RangoFichas)
                            .addComponent(botonMasRango)
                            .addComponent(botonMenosRango))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fondo.add(FondoGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 720, 300));

        FondoPt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FondoProyecto.jpg"))); // NOI18N
        Fondo.add(FondoPt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FondoPt2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/FondoProyecto.jpg"))); // NOI18N
        FondoPt2.setText("jLabel2");
        Fondo.add(FondoPt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 269, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonListoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void botonMasRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMasRangoActionPerformed

    private void botonMenosComodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosComodinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenosComodinActionPerformed

    private void botonMasComodin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasComodin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMasComodin1ActionPerformed

    private void botonMenosRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenosRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMenosRangoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfiguracionJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfiguracionJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonListo;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Comodines;
    private javax.swing.JPanel Fondo;
    private View.clases.PanelRound FondoCodigo;
    private javax.swing.JPanel FondoGris;
    private javax.swing.JLabel FondoPt1;
    private javax.swing.JLabel FondoPt2;
    private javax.swing.JLabel NumeroJugadores;
    private javax.swing.JLabel RangoFichas;
    private View.clases.PanelRound RegresarFondo;
    private javax.swing.JButton botonMasComodin1;
    private javax.swing.JButton botonMasRango;
    private javax.swing.JButton botonMenosComodin;
    private javax.swing.JButton botonMenosRango;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private View.clases.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
