package vistas;

import controladores.ControladorCrearPartida;
import controladores.ControladorMenu;
import modelos.ConstantesVentanas;
import modelos.ModeloMenu;
import modelos.ModeloObserver;
import modelos.Observable;

/**
 *
 * @author Katt
 */
public class JCrearPartida extends javax.swing.JFrame implements ModeloObserver {

    private ControladorCrearPartida controlador;

    /**
     * Creates new form JCrearPartida
     */
    public JCrearPartida(ControladorCrearPartida controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 160, 60));

        labelFondo.setIcon(new javax.swing.ImageIcon("C:\\Documentos\\ITSON\\Quinto Semestre\\Arquitectura de Software\\RummyEquipo6\\GUIs_Rummy\\src\\main\\java\\recursos\\fondos\\CrearPartidaImg.png")); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        controlador.mostrarMenu();
    }//GEN-LAST:event_btnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {

    }

    @Override
    public void cambiarVentana(int ventana) {
        if (ventana == ConstantesVentanas.JMENU) {
            this.setVisible(false);
            ModeloMenu m = new ModeloMenu();
            //Cargamos controlador y le asignamos qué modelo controlar
            ControladorMenu c = new ControladorMenu(m);
            //Cargamos 2 vistas y asignamos cual queremos que sea su controlador 
            JMenu v = new JMenu(c);
            //añadimos observadores al modelo. En este caso, dos vistas.
            m.addObservador(v);

        }
    }
}
