package vistas;

import controladores.ControladorCrearPartida;
import controladores.ControladorPerfil;
import controladores.ControladorUnirsePartida;
import modelos.ConstantesVentanas;
import modelos.ModeloCrearPartida;
import modelos.ModeloObserver;
import modelos.ModeloUnirsePartida;
import modelos.Observable;

/**
 *
 * @author Katt
 */
public class JPerfil extends javax.swing.JFrame implements ModeloObserver{
    private ControladorPerfil controlador;
    
    
    /**
     * Creates new form JPerfil
     */
    public JPerfil(ControladorPerfil controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConfirmar.setBorderPainted(false);
        btnConfirmar.setContentAreaFilled(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 270, 80));

        labelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\OMEN\\Documents\\GitHub\\RummyEquipo6\\GUIs_Rummy\\src\\main\\java\\recursos\\fondos\\Perfilimg.png")); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        controlador.mostrarUnirsePartida();
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        
    }

    @Override
    public void cambiarVentana(int ventana) {
        if (ventana == ConstantesVentanas.JUNIRSEPARTIDA) {
            this.setVisible(false);
            ModeloUnirsePartida m = new ModeloUnirsePartida();
            //Cargamos controlador y le asignamos qué modelo controlar
            ControladorUnirsePartida c = new ControladorUnirsePartida(m);
            //Cargamos 2 vistas y asignamos cual queremos que sea su controlador 
            JUnirsePartida v = new JUnirsePartida(c);
            //añadimos observadores al modelo. En este caso, dos vistas.
            m.addObservador(v);
        }
    }
}
