package mvc.vistas;

import mvc.cambioFrames.CambioFrameCrearPartida;
import mvc.controladores.ControladorCrearPartida;
import mvc.controladores.ControladorLobbyPartida;
import mvc.controladores.ControladorMenu;
import mvc.modelos.ConstantesVentanas;
import mvc.modelos.ModeloLobbyPartida;
import mvc.modelos.ModeloMenu;
import mvc.modelos.ModeloObserver;
import mvc.modelos.Observable;

/**
 *
 * @author Katt
 */
public class JCrearPartida extends javax.swing.JFrame implements ModeloObserver {

    private ControladorCrearPartida controlador;

    /**
     * Creates new form JCrearPartida
     */
    public JCrearPartida(ControladorCrearPartida controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        btnAumentarRangoComodines = new javax.swing.JButton();
        btnAumentarRangoFichas1 = new javax.swing.JButton();
        btnListo1 = new javax.swing.JButton();
        btnDisminuirRangoFichas1 = new javax.swing.JButton();
        btnDisminuirRangoComodines1 = new javax.swing.JButton();
        lblRangoMaximoComodines = new javax.swing.JLabel();
        lblRangoMaximoFichas = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(847, 485));
        setSize(new java.awt.Dimension(847, 485));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 160, 60));

        btnAumentarRangoComodines.setBorderPainted(false);
        btnAumentarRangoComodines.setContentAreaFilled(false);
        btnAumentarRangoComodines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarRangoComodinesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAumentarRangoComodines, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 30, 30));

        btnAumentarRangoFichas1.setBorderPainted(false);
        btnAumentarRangoFichas1.setContentAreaFilled(false);
        btnAumentarRangoFichas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarRangoFichas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAumentarRangoFichas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 30, 20));

        btnListo1.setBorderPainted(false);
        btnListo1.setContentAreaFilled(false);
        btnListo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListo1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnListo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 170, 50));

        btnDisminuirRangoFichas1.setBorderPainted(false);
        btnDisminuirRangoFichas1.setContentAreaFilled(false);
        btnDisminuirRangoFichas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirRangoFichas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisminuirRangoFichas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 30, 20));

        btnDisminuirRangoComodines1.setBorderPainted(false);
        btnDisminuirRangoComodines1.setContentAreaFilled(false);
        btnDisminuirRangoComodines1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuirRangoComodines1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisminuirRangoComodines1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, 20));

        lblRangoMaximoComodines.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRangoMaximoComodines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRangoMaximoComodines.setText("2");
        getContentPane().add(lblRangoMaximoComodines, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 50, 30));

        lblRangoMaximoFichas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRangoMaximoFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRangoMaximoFichas.setText("10");
        getContentPane().add(lblRangoMaximoFichas, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 50, 30));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/recursos/fondos/CrearPartidaImg.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 450));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAumentarRangoComodinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarRangoComodinesActionPerformed
        int valorActual = Integer.parseInt(lblRangoMaximoComodines.getText());
        if(valorActual != 8){
            controlador.sumarComodines();
        }
    }//GEN-LAST:event_btnAumentarRangoComodinesActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        controlador.mostrarMenu();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnListo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListo1ActionPerformed

    private void btnAumentarRangoFichas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarRangoFichas1ActionPerformed
        if(Integer.parseInt(lblRangoMaximoFichas.getText()) != 13){
            controlador.sumarRangoFichas();
        }
    }//GEN-LAST:event_btnAumentarRangoFichas1ActionPerformed

    private void btnDisminuirRangoFichas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirRangoFichas1ActionPerformed
        if(Integer.parseInt(lblRangoMaximoFichas.getText()) != 10){
            controlador.restarRangoFichas();
        }
    }//GEN-LAST:event_btnDisminuirRangoFichas1ActionPerformed

    private void btnDisminuirRangoComodines1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuirRangoComodines1ActionPerformed
        int valorActual = Integer.parseInt(lblRangoMaximoComodines.getText());
        if(valorActual != 2){
            controlador.restarComodines();
        }
    }//GEN-LAST:event_btnDisminuirRangoComodines1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAumentarRangoComodines;
    private javax.swing.JButton btnAumentarRangoFichas1;
    private javax.swing.JButton btnDisminuirRangoComodines1;
    private javax.swing.JButton btnDisminuirRangoFichas1;
    private javax.swing.JButton btnListo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel lblRangoMaximoComodines;
    private javax.swing.JLabel lblRangoMaximoFichas;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (arg instanceof CambioFrameCrearPartida) {
            CambioFrameCrearPartida cf = (CambioFrameCrearPartida) arg;

            // Verifica los valores que se están pasando
            System.out.println("Rango de Fichas: " + cf.getRangoFichas());
            System.out.println("Comodines: " + cf.getComodines());

            // Actualizamos el valor del JLabel
            lblRangoMaximoFichas.setText(String.valueOf(cf.getRangoFichas()));
            lblRangoMaximoComodines.setText(String.valueOf(cf.getComodines()));

            // Fuerza la actualización visual
            this.revalidate();
            this.repaint();
        }

    }

    @Override
    public void cambiarVentana(int ventana) {
        if (ventana == ConstantesVentanas.JMENU) {
            this.setVisible(false);
            ModeloMenu m = new ModeloMenu();
            //Cargamos controlador y le asignamos qué modelo controlar
            ControladorMenu c = new ControladorMenu(m);
            //Cargamos 2 vistas y asignamos cual queremos que sea su controlador 
            JMenu v = new JMenu(c);
            //añadimos observadores al modelo. En este caso, dos vistas.
            m.addObservador(v);
        } else if (ventana == ConstantesVentanas.JLOBBYPARTY) {
            this.setVisible(false);
            ModeloLobbyPartida m = new ModeloLobbyPartida();
            //Cargamos controlador y le asignamos qué modelo controlar
            ControladorLobbyPartida c = new ControladorLobbyPartida(m);
            //Cargamos 2 vistas y asignamos cual queremos que sea su controlador 
            JLobbyPartida v = new JLobbyPartida(c);
            //añadimos observadores al modelo. En este caso, dos vistas.
            m.addObservador(v);
        } 
    }
}
