package mvc.vistas;

/**
 *
 * @author Katt
 */
public class JResultados extends javax.swing.JFrame {

    /**
     * Creates new form JResultados
     */
    public JResultados() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTercero = new javax.swing.JLabel();
        txtGanador = new javax.swing.JLabel();
        txtSegundo = new javax.swing.JLabel();
        btnRegresarMenu = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTercero.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        txtTercero.setForeground(new java.awt.Color(255, 255, 255));
        txtTercero.setText("JugadorTercero");
        getContentPane().add(txtTercero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, 30));

        txtGanador.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        txtGanador.setForeground(new java.awt.Color(255, 255, 255));
        txtGanador.setText("JugadorGanador");
        txtGanador.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtGanadorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(txtGanador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, 30));

        txtSegundo.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        txtSegundo.setForeground(new java.awt.Color(255, 255, 255));
        txtSegundo.setText("JugadorSegundo");
        getContentPane().add(txtSegundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, 30));

        btnRegresarMenu.setBorder(null);
        btnRegresarMenu.setBorderPainted(false);
        btnRegresarMenu.setContentAreaFilled(false);
        getContentPane().add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 210, 90));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/recursos/fondos/ResultadosImg.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGanadorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtGanadorAncestorAdded
        
    }//GEN-LAST:event_txtGanadorAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JResultados().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel txtGanador;
    private javax.swing.JLabel txtSegundo;
    private javax.swing.JLabel txtTercero;
    // End of variables declaration//GEN-END:variables
}
