/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mvc.vistas;

import mvc.controladores.ControladorTablero;
import mvc.modelos.ModeloTablero;

/**
 *
 * @author PERSONAL
 */
public class JTablero extends javax.swing.JFrame {

    ControladorTablero controlador;
    
    /**
     * Creates new form JTablero
     */
    public JTablero() {
        initComponents();
        ModeloTablero m = new ModeloTablero();
        controlador = new ControladorTablero(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJalarFicha = new javax.swing.JButton();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJalarFicha.setBorderPainted(false);
        btnJalarFicha.setContentAreaFilled(false);
        btnJalarFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJalarFichaActionPerformed(evt);
            }
        });
        getContentPane().add(btnJalarFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 140, 130));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mvc/recursos/fondos/fondoTablero.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJalarFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJalarFichaActionPerformed
        
    }//GEN-LAST:event_btnJalarFichaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJalarFicha;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
}
